/* eslint-disable max-len */
import * as Typography from '../global/typography';

export const link = { ...Typography.getStyles({ size: 2, weight: '700', color: 'primary', decoration: 'underline' }) };
export const title = { ...Typography.getStyles({ size: 4, weight: '700', color: 'primary' }) };
export const regular = { ...Typography.getStyles({ color: 'semiGrey', size: 2, weight: '500' }) };
export const error = { ...Typography.getStyles({ color: 'error', size: 4, weight: '700' }) };
export const errorSmall = { ...Typography.getStyles({ color: 'error', size: 1, weight: '500' }) };
export const titleSecondary = { ...Typography.getStyles({ size: 4, weight: '700', color: 'secondary' }) };
export const titleSecondaryLight = { ...Typography.getStyles({ size: 4, weight: '700', color: 'secondaryLight' }) };
export const titlePrimaryLarge = { ...Typography.getStyles({ size: 5, weight: '700', color: 'primary' }) };
export const titleSecondaryLarge = { ...Typography.getStyles({ size: 5, weight: '700', color: 'secondary' }) };
export const titleSmall = { ...Typography.getStyles({ size: 3, weight: '700', color: 'primary' }) };
export const titleSmallWhite = { ...Typography.getStyles({ size: 3, weight: '700', color: 'white' }) };
export const titleSmallSecondaryLight = { ...Typography.getStyles({ size: 3, weight: '700', color: 'secondaryLight' }) };
export const titleSmallSuccess = { ...Typography.getStyles({ size: 3, weight: '700', color: 'success' }) };
export const titleSmallError = { ...Typography.getStyles({ size: 3, weight: '700', color: 'error' }) };
export const boldSecondary = { ...Typography.getStyles({ size: 2, weight: '700', color: 'secondary' }) };
export const boldWhite = { ...Typography.getStyles({ size: 2, weight: '700', color: 'white' }) };
export const boldGrey = { ...Typography.getStyles({ size: 2, weight: '700', color: 'grey' }) };
export const boldSmallGrey = { ...Typography.getStyles({ size: 1, weight: '700', color: 'grey' }) };
export const regularSmall = { ...Typography.getStyles({ size: 1, weight: '500', color: 'semiGrey' }) };
export const regularSmallGrey = { ...Typography.getStyles({ size: 1, weight: '500', color: 'grey' }) };
export const regularSmallSuccess = { ...Typography.getStyles({ size: 1, weight: '500', color: 'success' }) };
export const regularSmallError = { ...Typography.getStyles({ size: 1, weight: '500', color: 'error' }) };
export const regularSmallDark = { ...Typography.getStyles({ size: 1, weight: '500', color: 'dark' }) };
export const regularPrimary = { ...Typography.getStyles({ size: 1, weight: '500', color: 'primary' }) };
export const regularSecondary = { ...Typography.getStyles({ size: 1, weight: '500', color: 'secondary' }) };
export const light = { ...Typography.getStyles({ size: 2, weight: '300', color: 'semiGrey' }) };
export const lightPrimarySmallest = { ...Typography.getStyles({ size: 0, weight: '300', color: 'primary' }) };
export const lightSecondarySmallest = { ...Typography.getStyles({ size: 0, weight: '300', color: 'secondary' }) };
export const lightTextCenter = { ...Typography.getStyles({ size: 1, weight: '500', color: 'secondaryLighter', align: 'center', height: 22 }) };
